apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: laravel-prod
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/bdaley/openshift-laravel-pgsql.git
    targetRevision: main
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: laravel-prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
