apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - configmap.yaml
  - secret.yaml
  - pvc-database.yaml
  - pvc-storage.yaml
  - service.yaml
  - route.yaml
  - deployment.yaml

labels:
  - pairs:
      app.kubernetes.io/name: laravel-web
      app.kubernetes.io/part-of: openshift-laravel-sqlite
