apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: laravel-staging

resources:
  - ../../base

patches:
  - path: route-host-patch.yaml
  - path: deployment-image-patch.yaml

configMapGenerator:
  - name: laravel-web-config
    behavior: merge
    literals:
      - APP_ENV=staging
      - APP_URL=https://laravel-staging.apps.example.com
      - LOG_LEVEL=debug

generatorOptions:
  disableNameSuffixHash: true
